### PR TITLE
Added include to manifests, and empty hashse to empty data files

### PR DESCRIPTION
**Pull request by calmenergy**
Added "include ::tcpwrappers" to allow.pp, config.pp, and install.pp This is necessary because those manifests reference variables that are defined in init.pp.

Added "{}" to the files in data/osname that were empty. Apparently some versions of yaml don't like an empty file; adding the empty hash made the errorrs I was getting with the spec tests, go away.

### CODE REVIEW

**Comment by millerjl1701** [comment]
@calmenergy , thanks for the PR! 

I had on my to do list to figure out the empty yaml file problem as I was also seeing the following in my puppetserver log files:
`
Puppet /etc/puppetlabs/code/environments/resiihgclin/modules/tcpwrappers/data/osname/CentOS-7.yaml: file does not contain a valid yaml hash
`

The code you propose to add is in line with: https://tickets.puppetlabs.com/browse/PUP-7414. So, thank you for submitting this solution as it saved me a lot of time to figure out!

However, the includes are not needed for variable access with the versions of puppet this module supports. For examples of the contain coding style and parameter access, please see the following Puppet Supported or Approved modules that I use in my environments:

- https://github.com/puppetlabs/puppetlabs-ntp/
- https://github.com/puppetlabs/puppetlabs-postgresql/
- https://github.com/voxpupuli/puppet-collectd/
- https://github.com/voxpupuli/puppet-logrotate/
- https://github.com/elastic/puppet-elasticsearch/

So, going forward, would you please redo this PR so that it only contains the hiera files changes. If there is a particular error log that you are fixing with the includes, please open a different/issue PR, provide the errors you are experiencing, and I will reconsider on the separate PR.

**Comment by calmenergy** [comment]
I am unlikely to get around to the extra work you are requesting until I do a big upgrade of lots of things to puppet 5. Please free to cancel the PR and I will use my forked copy.  I’m glad I was able to help with the empty yaml problem

**Comment by millerjl1701** [comment]
No worries, I'll merge the above and then make changes from there. Thanks again @calmenergy .

**Comment by calmenergy** [comment]
I am dreading the big upgrade to 5 and it may be a while before I can force myself to do it... On Jul 24, 2018 1:36 PM, Jeffrey Miller <notifications@github.com> wrote:Merged #1.

**Comment by millerjl1701** [comment]
Puppet module incorporating this PR: mod 'millerjl1701-tcpwrappers', '1.1.2'

Thanks again!

**Pull request merged**
